---
- name: Configure the Debian VM, ready to run Docker containers
  hosts: vm
  remote_user: automatedscriptrunner
  become: true

  roles:
    - firewalld
    - sshd
    - configure-root-user
    - docker
    - chrony
