---
# Install required software, but actually do so.
# These unhelpful comments will bite me later.
# hardcodes: amd64 architecture, Debian bullseye

- name: Install GnuPG (for apt_key)
  apt:
    name:
      - gnupg
    state: latest  # noqa package-latest
    update_cache: true

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker apt repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian bullseye stable
    state: present

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest  # noqa package-latest
    update_cache: true
