---
- name: install and start nginx
  hosts: vm
  vars:
    http_port: 8050
  remote_user: root

  tasks:
    - name: install nginx
      apt:
        pkg: nginx
        state: latest
    - name: start nginx
      service:
        name: nginx
        state: started
        enabled: yes
