---
# Configure Docker daemon for IPv6 on containers
# (this is not telling Docker to use IPv6 for pulling images)

# hardcodes: amd64 architecture, Debian bullseye

- name: Install GnuPG (for apt_key)
  apt:
    name:
      - gnupg
    state: latest  # noqa package-latest
    update_cache: true

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker apt repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian bullseye stable
    state: present

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: latest  # noqa package-latest
    update_cache: true

- name: Copy docker daemon.json
  copy:
    src: docker-daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  tags: docker
  notify:
    - Restart Docker

- name: Start Docker
  service:
    name: docker
    state: started
    enabled: true
  tags: docker

- name: Create directory for Docker Compose
  file:
    path: /usr/local/lib/docker/cli-plugins
    state: directory

- name: Install Docker Compose v2.2.3
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64
    checksum: sha256:https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64.sha256
    dest: /usr/local/lib/docker/cli-plugins/docker-compose
    owner: root
    group: root
    mode: 0755

- name: Symlink Docker Compose
  file:
    src: /usr/local/lib/docker/cli-plugins/docker-compose
    dest: /usr/local/bin/docker-compose
    state: link
