---
# Configure Docker daemon for IPv6 on containers
# (this is not telling Docker to use IPv6 for pulling images)

- name: Copy docker daemon.json
  template:
    src: docker-daemon.json
    dest: /etc/docker/daemon.json

- name: Restart docker
  service:
    name: docker
    state: restarted
