---
- name: Disable SSH password authentication (and use only SSH keys)
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^#PasswordAuthentication'
    line: 'PasswordAuthentication no'
    # validate: 'sshd -t'
  notify:
    - Reload sshd

- name: Disable login as root using SSH
  lineinfile:
    dest: /etc/ssh/sshd_config
    state: present
    regexp: '^#PermitRootLogin prohibit-password'
    line: 'PermitRootLogin no'
    # validate: 'sshd -t'
  notify:
    - Reload sshd

- name: Enable sshd on boot
  service:
    name: sshd
    enabled: true
