---
# Installs software directly on the VM, e.g. docker
# and generally configures the host (e.g. setting time server)

# Assumes that playbook is running as a dedicated passwordless user
# with NOPASSWD in sudoers for the dedicated user

- name: Disable password login over SSH
  hosts: vm
  become: true

  roles:
    - disable-ssh-password-auth

- name: Disable root user login
  hosts: vm
  become: true

  roles:
    - disable-root-user

- name: Install Docker
  hosts: vm
  become: true

  roles:
    - install-docker

- name: Configure Docker daemon (for IPv6)
  hosts: vm
  become: true

  roles:
    - configure-docker
